### ISSUE TITLE
branch name of the commits where the secrets detected

### ISSUE THREAD

**Issue by arunanandhan** [zricethezav/gitleaks#1129]
Is there a way to get the branch name of the commits where the secrets detected? Also Is there a way to have one more field that tells, if the secret is currently in github or its past commits?(means now its removed)

cc @zricethezav

**Comment by zricethezav** [comment]
@arunanandhan no, gitleaks does not expose branch names since gitleaks operates on commits and commits can be associated with many branches. 

> Also Is there a way to have one more field that tells, if the secret is currently in github or its past commits?(means now its removed)

If `commit` is set in the report or output that means the secret is in the git history and will be forever, or until you rewrite your git history (note that rewriting git history isn't a good solution to prevent secret leaks as copies containing secrets might still be out in the wild)
