### ISSUE TITLE
gitleaks scan bypasses RSA key 

### ISSUE THREAD

**Issue by vikten22** [zricethezav/gitleaks#138]
This happens for some of my repositories when i did scan today. However, the same scan has been done on October 17th, listed all leaks but now it doesn't for few repositories. The same RSA keys have been identified in some repo's and got listed in the report.

I did check the files where it actually found leaks in my last scan. The keys still exists.
No changes made to those repositories from last 4 months.

Can anyone help on this. Will provide any information if required.

**Comment by vikten22** [comment]
@zricethezav could you please help me on this.

**Comment by zricethezav** [comment]
Nothing has changed between now and Oct 17th that would have changed the scan. Are you using the default regex or your own `--config=` config file?

**Comment by vikten22** [comment]
I am using the default file.

**Comment by zricethezav** [comment]
I would recommend committing to the same repo a dummy file containing an RSA key.

**Comment by vikten22** [comment]
I will try that and let you know.

**Comment by vikten22** [comment]
I did commit few new files from the same repo. The scan captures the new files with secrets. These secrets which i added in new file were same copied from existing files of same repo. However the old files are not working.

Can i get a gitleaks tool version before oct 18.

**Comment by zricethezav** [comment]
try https://github.com/zricethezav/gitleaks/releases/tag/v1.12.0

**Comment by zricethezav** [comment]
@tluolamo @vikten22 Thanks for nailing down the version number. 1.16 introduced full tree coverage in that instead of inspecting a patch for `curr commit vs prev commit` 1.16 gitleaks compares `curr commit vs all of curr commit's parents`. It could be that version 1.15 was generating a false positive as `git rev-list --all` doesn't actually traverse a tree. Can you confirm that the leak caught by 1.15 is from a valid commit? Any other general information about he commit you can tell me? how many parents, is it the first commit/last commit? etc

**Comment by tluolamo** [comment]
it was not a false positive. It was tfstate file which has real RSA keys in it.

**Comment by zricethezav** [comment]
is that commit accounted for in another leak?

**Comment by zricethezav** [comment]
Gotcha, and the leak was introduced in the first commit? If thats the case i think i know whatsup. first commit edge case as the first commit does not have any parents...

**Comment by tluolamo** [comment]
Yes very first commit to the repo. This was a repo created for certain training, so it wasn't very active and the initial commit was pretty huge.

**Comment by zricethezav** [comment]
gotcha, ill try and put in a fix asap for ya.

**Comment by tluolamo** [comment]
Thank you, I'd certainly look into fixing myself, but not super familiar with Go yet.

**Comment by zricethezav** [comment]
@vikten22 @tluolamo try https://github.com/zricethezav/gitleaks/releases/tag/v1.19.2
thanks for pointing this out

**Comment by zricethezav** [comment]
@tluolamo thanks for the response. 

https://github.com/zricethezav/gitleaks/pull/146/files Looking at this change I can see that the initial commit is not counted towards "total commits" analyzed. I'll have to fix that. That is why you are seeing "0 commits inspected". 

As to why you are seeing 2 leaks detected between 1.16.0 vs 1.19.2 is most likely because gitleaks now checks ALL branches by default. Gitleaks makes sure not to do redundant work by memoizing a table of a commit + parent commit hash. However, the initial commit skips this. Youre most likely seeing two commits from HEAD and ref/origin/master. I'll have to put in another fix for this.

**Comment by zricethezav** [comment]
@tluolamo 1.19.3 released. try that, you should see 1 leak detected, 1 commit inspected hopefully

**Comment by vikten22** [comment]
@zricethezav  we will try 1.19.3 version and update you.

**Comment by vikten22** [comment]
@zricethezav  My scan results were accurate with 1.19.3 when compared with results from 1.19.2
We will update after @tluolamo scans using 1.19.3. Then we will compare both of our results.

Thank you @zricethezav  for a quick update on our issue.

**Comment by tluolamo** [comment]
OK 1.19.3 got me
1 leaks detected. 1 commits inspected in 8 milliseconds

In my test scenario, I also verified some other repos where now I have no/fewer dupes at least so I this is great. Thanks so much.

**Comment by zricethezav** [comment]
Awesome, thanks for digging this up for me @tluolamo @vikten22 gonna close this one out
