### ISSUE TITLE
bug? No commits were scanned

### ISSUE THREAD

**Issue by the1mills** [zricethezav/gitleaks#214]
I have this command:

    gitleaks  \
        --ssh-key='/keys/ssh/values/bucket' \
        --repo "$line"

I loop over my org's repo urls, we have 100+ repos.

I see this in my logs:

```console
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/metavana-webapp.git 
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/productionappserver.git 
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/concepts_adaptive_engine.git 
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/datavana.git 
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/products-tools.git 
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/mrapi.git  
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/entitycollection.git 
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/discogsapi.git 
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/web3.git   
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/tagvana.wikipedia2.git 
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
INFO[2019-05-10T23:26:39Z] cloning git@bitbucket.org:interos/pwp.git    
INFO[2019-05-10T23:26:39Z] 0 leaks detected. 0 commits inspected in     
```

so it looks like the clones all worked, ssh-key is good, but never any commits inspected, always 0? why would that be?

**Comment by zricethezav** [comment]
I'm not sure what the issue could be. I tried cloning a bunch of private repos using a custom ssh-key path and it worked fine. Gitleaks is recognizing that you have supplied a valid ssh key otherwise you would be seeing this error message: https://github.com/zricethezav/gitleaks/blob/master/src/config.go#L230-L232

**Comment by electrofelix** [comment]
@zricethezav I've seen a problem were an unparseable gitleaks.toml file will result in the above instead of erroring out.

Simply adding `--repo-config` without a valid .gitleaks.toml file in the root of the repository triggers it. When looking at the code I spotted the following line:
https://github.com/zricethezav/gitleaks/blob/3b6c198715026ddfa7d6a68ba371e84c0f5c6197/src/repo.go#L147

Which in the case of an error from `updateFromRepo`, which looks like it returns the current leaks and nil as the error to the caller instead of `err`.

By comparison, when auditing a branch further down in the same file at:
https://github.com/zricethezav/gitleaks/blob/3b6c198715026ddfa7d6a68ba371e84c0f5c6197/src/repo.go#L168
I see it returning `err` in the case that it's not nil.

Looking around the code I see the pattern of testing and then returning nothing for `err` at:
https://github.com/zricethezav/gitleaks/blob/3b6c198715026ddfa7d6a68ba371e84c0f5c6197/src/repo.go#L155 
https://github.com/zricethezav/gitleaks/blob/3b6c198715026ddfa7d6a68ba371e84c0f5c6197/src/repo.go#L198
https://github.com/zricethezav/gitleaks/blob/3b6c198715026ddfa7d6a68ba371e84c0f5c6197/src/repo.go#L335
https://github.com/zricethezav/gitleaks/blob/3b6c198715026ddfa7d6a68ba371e84c0f5c6197/src/repo.go#L350

I'm not very familiar with golang, but given that normally I'd expect to see something output a log message or doing something about the error, are these just silently squashing errors and returning before the scanning gets performed resulting the output above?

Should I log a separate issue for the `--repo-config` or are they all just the same and can be handled under this issue?

**Comment by hughsaunders** [comment]
Other issue for `--repo-config` silently failing with an invalid config file: https://github.com/zricethezav/gitleaks/issues/248

**Comment by bufferoverflow** [comment]
@themills You should use `--repo="$line"` the following should work:

```
gitleaks  \
    --ssh-key='/keys/ssh/values/bucket' \
    --repo="$line"
```

**Comment by w0rmr1d3r** [comment]
Hello @the1mills !

Has this been solved?
Can you try with newer versions fo gitleaks?

Thank you!

**Comment by zricethezav** [comment]
gitleaks is not responsible for cloning in v8+
