### ISSUE TITLE
Let's talk exit codes

### ISSUE THREAD

**Issue by zricethezav** [zricethezav/gitleaks#271]
Hey all. First of all I know the issues are piling up but I plan on addressing them in the coming weeks. I was out for a while where I didn't touch my computer due to bereavement, but now I'm back at my desk hacking away. 

Taking a look at the code, I kind of want to do another rewrite... it's a bit messy and has some pretty nasty go anti-patterns, I want to fix these in the next big release. 

So speaking of next releases one thing I want to get a feel for is the use of exit codes. Are people happy with the exit codes now? I'm realizing that if leaks are detected we return 1, which is usually used if an application encounters errors. 

What are your thoughts?

**Comment by mindriven** [comment]
I'd leave it as it is, I like it, it allows me to know what the result of the run is, I use that in a script that I use to scan multiple repositories.
One option to keep everyone happy would be to provide a flag that allows to steer this behavior.. just not sure if there's a demand for it

**Comment by galiagante** [comment]
I concur with leaving the current exit code intact, but adding another code to depict the occurrence of the actual error event after a failed run is a good idea. There is precedent for this in numerous command-line utilities and it doesn't seem like much of a lift to add in such a return code. I question the utility of anything more than one error exit code, however.

As far as rewrites go, I recall some discussion of switching over to Rust in order to take advantage of faster regex processing?

**Comment by lagold27** [comment]
I agree, more exit codes would be helpful to determine issues with authenticating with git.
