### ISSUE TITLE
Report showing N/A in Line column when scanning an organisation

### ISSUE THREAD

**Issue by WaiLoonTan** [zricethezav/gitleaks#351]
Describe the bug
The report when scanning repos in an organisation only states N/A as line..

To Reproduce
Scan all repos in an organisation.

Expected behavior
Line should show which line is the code of the problem.

Basic Info (please complete the following information):

OS: Windows 10
Gitleaks Version: 4.1.0
GO version : 1.12

Additional context
N/A

cc @zricethezav

**Comment by GolanTrevize10** [comment]
@zricethezav I think the problem is if there is a new line character in the commit message, that is not removed when generating csv reports and then the report is malformed.

**Comment by GolanTrevize10** [comment]
@zricethezav I thin the file rules are not working properly. I tried with a config file just with one rule like this
`[[rules]]
    description = "PEM Files"
    file = '''(.*)?pem$'''
    tags = ["key", "PEM"]
`
and I get many leaks like this 

{
  "line": "N/A",
  "offender": "Filename/path offender: sonar-project.properties",
  "commit": "d8691ae8dd999375aef0c2848726e7851238f1f7",
  "repo": "post-clearance-notification-mq",
  "rule": "PEM Files",
  "commitMessage": "perm change\n",
  "author": "xxxxx",
  "email": "xxxxx",
  "file": "sonar-project.properties",
  "date": "2017-04-28T09:37:54+02:00",
  "tags": "key, PEM"
 }

That leak should not trigger the rule because the file is not a pem file.

**Comment by GolanTrevize10** [comment]
ah I found the issue. I was using the file property in the rule instead of filenameregex. With filenameregex it works. I think you should update the example in https://github.com/zricethezav/gitleaks/blob/master/examples/regex_and_file.toml because it is wrong.

**Comment by zricethezav** [comment]
@GolanTrevize10 thanks for pointing that out. I added some validation in this PR: https://github.com/zricethezav/gitleaks/pull/412. It'll go in the next release.
