### ISSUE TITLE
Support ignore annotations for detected secrets

### ISSUE THREAD

**Issue by theoretick** [zricethezav/gitleaks#419]
**Is your feature request related to a problem? Please describe.**

In certain cases we may want to ignore instances of secrets that would be considered false positives. This is distinct form the allow/deny configuration within `gitleaks.toml` since we want to keep a regex enabled but only ignore a single instance.

**Describe the solution you'd like**

Add an annotation (TBD) to ignore detected secrets and not report them.

**Describe alternatives you've considered**

I'm not sure what alternatives would be available 🤔 

**Additional context**

See related discussion https://gitlab.com/gitlab-org/gitlab/-/issues/11479#note_392501667

cc @zricethezav

**Comment by zricethezav** [comment]
@theoretick an alternative could be to add a `regex` entry in the [global allowlist ](https://github.com/zricethezav/gitleaks/blob/master/config/default.go#L134-L138)field rather than adding another option to the cli. This would allow users the ability to define their own "ignore this line" signature. WDYT?

**Comment by theoretick** [comment]
> @theoretick an alternative could be to add a regex entry in the global allowlist field rather than adding another option to the cli. This would allow users the ability to define their own "ignore this line" signature. WDYT?

Sorry for the slow reply, yes I think that makes sense and is a really great boring solution. Thanks for this!
