### ISSUE TITLE
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### ISSUE THREAD

**Issue by yxingwu** [zricethezav/gitleaks#540]
**Describe the bug**
I am using gitleaks to clone **gist**, but got the error `ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`
Probably, it's a bug. I used gitleaks to clone gist repository in `https`, it works fine. But I used gitleaks to clone gist repository in `ssh`, got the error. I did it by `git clone git@gist.github.com:0116ae46ac5bedxxxx.git` command directly, the repository can be cloned successfully .
**To Reproduce**
Run the gitleaks command
`gitleaks  --files-at-commit latest --repo-url gist.github.com:xxx/xxx.git --clone-path /home/xxx/ --report /home/test.json`
got the error:  `ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

`gitleaks  --files-at-commit latest --repo-url https://gist.github.com/xxx.git --clone-path /home/xxx/ --report /home/test.json`, it works fine.
Using git command directly, `git clone git@gist.github.com:0116ae46ac5bedxxxx.git` , the repository can be cloned successfully .
**Expected behavior**
Clone gist repository successfully, no error.

**Basic Info (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Gitleaks Version: V7.2.1

cc @zricethezav

**Comment by davidkochkerian** [comment]
issue present in older versions as well, please fix...

**Comment by davidkochkerian** [comment]
Looks like the code has 2 issues.

1. It's only looking at id_rsa, so if you have a configuration for multiple keys, say one for github, and another for gitlab, you'll need to make sure id_rsa is set to the one that you are scanning... you should instead check config, and use the appropriate key, or alternatively try all keys in .ssh folder...

2. you are not taking account keys that are passkey protected
ssh: this private key is passphrase protected

this can also be solved by allowing native git to do the auth instead of your code trying to figure out what to do..., if passkey is in keychain, it'll work automatically...

**Comment by zricethezav** [comment]
@davidkochkerian happy to look at PRs. My time is gonna be tight for the next few months so this might not get my full attention for a while.

**Comment by zricethezav** [comment]
Gitleaks has been updated to [v8.0.0](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0) and this issue will not be 
fixed moving forward. Sorry for the inconvenience, feel free to fork older versions introduce a fix in your fork.

Gitlaeks is not responsible for cloning
