### ISSUE TITLE
File with key not detected as leak

### ISSUE THREAD

**Issue by Normo** [zricethezav/gitleaks#580]
**Describe the bug**
It seems that gitleaks does not detect files according to the following rule:
```toml
[[rules]]
	description = "Files with keys and credentials"
	files = '''(?i)(id_rsa|passwd|id_rsa.pub|pgpass|pem|key|shadow)'''
```
Instead it reports that this rule *"does not define any actionable data"*:
```
time="2021-06-03T10:09:25Z" level=warning msg="Rule Files with keys and credentials does not define any actionable data"
time="2021-06-03T10:09:25Z" level=info msg="scan time: 2 milliseconds 420 microseconds"
time="2021-06-03T10:09:25Z" level=info msg="No leaks found"
```
I'm not sure if it's a bug or misconfiguration.

**To Reproduce**
1. Create an empty directory:
    ```shell
    $ mkdir /tmp/my-repo
    $ cd /tmp/my-repo
    ```
2. Create SSH key pair:
    ```shell
    $ ssh-keygen -t rsa -f /tmp/my-repo/id_rsa
    ```
3. Download example config [`leaky-repo.toml`](https://github.com/zricethezav/gitleaks/blob/master/examples/leaky-repo.toml):
    ```shell
    $ curl -sO https://raw.githubusercontent.com/zricethezav/gitleaks/master/examples/leaky-repo.toml
    $ ls /tmp/my-repo
    id_rsa  id_rsa.pub  leaky-repo.toml
    ```
4. Run gitleaks:
    ```shell
    $ docker run --rm -v ${PWD}:/my-repo zricethezav/gitleaks:latest --path="/my-repo" --no-git --config-path="/my-repo/leaky-repo.toml" -v
    time="2021-06-03T10:09:25Z" level=warning msg="Rule Files with keys and credentials does not define any actionable data"
    time="2021-06-03T10:09:25Z" level=info msg="scan time: 2 milliseconds 420 microseconds"
    time="2021-06-03T10:09:25Z" level=info msg="No leaks found"
    ```
**Expected behavior**
I would expect gitleaks to detect the file `id_rsa` as a leak.

**Basic Info (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - Gitleaks Version: v7.5.0

cc @zricethezav

**Comment by w0rmr1d3r** [comment]
Hello @Normo !

I created a key pair and ran gitleaks and it has found it.

What I did was to create a key from scratch with just `ssh-keygen`.
Named it `test-gitleaks` and of course, it generated `test-gitleaks` and `test-gitleaks.pub`  files.

In that very same folder I ran `gitleaks --no-git --path=. --verbose` and of course, it found a leak, which is the key I generated before.

I have the same gitleaks version, installed with brew in my case.

I ran gitleaks as a docker:
`docker run -v ${PWD}:/my-repo zricethezav/gitleaks:latest --path="/my-repo" --no-git --verbose` and the output is the same.

I think the only difference is that I don't have a custom rules file, since gitleaks by default already detects private keys.
Can you try to run it without your rules?

Thank you!

**Comment by twierzchowski** [comment]
There is a typo in example. It should be ```file``` instead of ```files``` in configuration example.
```
[[rules]]
	description = "Files with keys and credentials" 
	file = '''(?i)(id_rsa|passwd|id_rsa.pub|pgpass|pem|key|shadow)'''
```

**Comment by zricethezav** [comment]
@twierzchowski @w0rmr1d3r thanks for catching this 😄
