### ISSUE TITLE
ERR fatal: unrecognized argument: --show-pulls

### ISSUE THREAD

**Issue by codekuu** [zricethezav/gitleaks#705]
**Describe the bug**
When I try to run gitleaks I get the following error:
```
$ gitleaks detect .
    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

9:01AM ERR fatal: unrecognized argument: --show-pulls
```

Currently running Linux Mint 20.

**To Reproduce**
Run `gitleaks detect .` in a local repository

**Expected behavior**
Should start to detect secrets but does not.

**Screenshots**
X

**Basic Info (please complete the following information):**
 - OS: Linux Mint 20.2
 - Gitleaks Version: 8.0

**Additional context**
Not sure where "--show-pulls" comes from. Git has no --show-pulls and from what I can see neither do gitleaks.

cc @zricethezav

**Comment by codekuu** [comment]
I am happy with `gitleaks detect --no-git` for now, closing.

**Comment by zricethezav** [comment]
@codekuu thank you for opening this issue. You actually bring up a bug that should be fixed. `--show-pulls` was introduced in git `2.27` see https://github.com/git/git/blob/master/Documentation/RelNotes/2.27.0.txt#L69-L72 for git's release notes. I believe `--show-pulls` should be removed since it shows merge commits which don't introduce any new information in the commit history.
