### ISSUE TITLE
Add commit scan information when log level is debug

### ISSUE THREAD

**Issue by JoostVoskuil** [zricethezav/gitleaks#711]
Hi @zricethezav ,

Congrats on v8! Awesome work. At the moment I am adjusting the Azure DevOps extension to work with v8. I really like the way you are continuing with v8, making it simpler and to-the-point.

I notice that I find it hard to find out what commits are actually scanned by Gitleaks. Maybe it is just the imposter-syndrome kicking in but I don't feel that I am in control when providing a range of commits with the --log-opts. 

Is it possible to give more information when the log level is set to debug that Gitleaks give more output? For example what are the commits that are scanned and the number of commits processed?

cc @zricethezav

**Comment by zricethezav** [comment]
@JoostVoskuil 
This is something I'll have to think about. You can see the `git log` command that gitleaks is parsing. From that you can alter the command to give you the number of commits scanned.

ex: if I run `gitleaks detect --log-level=debug --log-opts=-50` I'm telling gitleaks to scan with a depth of 50 commits.

The `git log` command executed is `git -C . log -p -U0 -50`

You can follow up with `git -C . log --oneline -50 | wc -l` to see number of commits scanned.

I just whipped up https://github.com/zricethezav/gitleaks/compare/commit-debug-log?expand=1 but am unsure if I want to add this as it might confuse folks since the number of commits scanned might be lower than the output of `git -C . log --oneline -50 | wc -l` due to empty commits/no additions/file name changes

**Comment by zricethezav** [comment]
I actually think this might be worthwhile since it has to be enabled via log-level setting, thanks for opening this @JoostVoskuil

**Comment by JoostVoskuil** [comment]
Cool! Awesome

**Comment by zricethezav** [comment]
released in v8.0.4, thanks @JoostVoskuil
