### ISSUE TITLE
Gitleaks should honor repo root configuration

### ISSUE THREAD

**Issue by paul-m** [zricethezav/gitleaks#733]
**Describe the bug**

If you invoke gitleaks from a subdirectory of a repo, it does not find the root of the repo while looking for configuration.

**To Reproduce**

Run gitleaks at the root directory of a repo. It will generate a `.gitleaks.toml` file there.

Change directories to any other directory within the repo.

Re-run gitleaks. Gitleaks now uses the default configuration rather than the one in the repo root, and generates another `.gitleaks.toml` file.

**Expected behavior**

If my CWD is within the repo, the repo config should be used during detection.

**Screenshots**

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
> If my CWD is within the repo, the repo config should be used during detection.

@paul-m 
I don't agree with the bug label. If your CWD is not at the root of the repo then you should use `--config-path` to specify the config otherwise gitleaks will use the path specified in the soon to be fixed documentation of `--config-path`: 

```
config file path
order of precedence: 
1. --config/-c 
2. (--source/-s)/.gitleaks.toml
if --config/-c is not set and no (--source/s)/.gitleaks.toml present 
then .gitleaks.toml will be written to (--source/-s)/.gitleaks.toml for future use
```

Note: `--source/s` defaults to `.`

This is an enhancement as it would require gitleaks to check if the `--no-git` flag is present. If its _not_ present then we could figure out what the repo root is by using `git rev-parse --show-toplevel`. However, `--show-toplevel` is not available in all recent versions of `git`, it was introduced in `2.25`. You could use `git rev-parse --show-cdup` instead if the version of git is older than `2.25`. I'm not going to commit time right now to fix this although I will happily review PRs if people are interested in contributing.

**Comment by zricethezav** [comment]
Alternatively I could make `--source` mandatory which would resolve this issue.

**Comment by paul-m** [comment]
Thanks.

"If your CWD is not at the root of the repo then you should use --config-path to specify the config"

Well, that's the issue. I don't think you should have to, and I wasted an afternoon on the assumption that you wouldn't have to. :-)

I'd say it's a bug because it's going to drop a bunch of extra .gitleaks.toml config files in my repo that will then become false positives.

Thanks again for your time.

**Comment by zricethezav** [comment]
> I'd say it's a bug because it's going to drop a bunch of extra .gitleaks.toml config files in my repo that will then become false positives.

I'll fix this by defaulting to ignore any config tomls

**Comment by zricethezav** [comment]
Closing this as I have changed my mind. I don't want gitleaks to be responsible for finding the root of the repo when you can use `--config-path` or `GITLEAKS_CONFIG` env var to load configs. 

New config usage:
```
  -c, --config string          config file path
                               order of precedence:
                               1. --config/-c
                               2. env var GITLEAKS_CONFIG
                               3. (--source/-s)/.gitleaks.toml
                               If none of the three options are used, then gitleaks will use the default config
```
