### ISSUE TITLE
Does it support scanning all the branches?

### ISSUE THREAD

**Issue by vivekyad4v** [zricethezav/gitleaks#753]
If I run a scan against an existing huge repo, will it scan all the branches that exist in a repo?

**Comment by zricethezav** [comment]
@vivekyad4v by default yes since `--all` is passed into the `git log` command (see here https://github.com/zricethezav/gitleaks/blob/master/git/git.go#L26-L27 ). If you want to have more control and specify a branch you can use `--log-opts={branch_name}`. 

https://git-scm.com/docs/git-log for reference
