### ISSUE TITLE
gitleaks_8.2.7_windows_x64.zip

### ISSUE THREAD

**Issue by sergiomarotco** [zricethezav/gitleaks#772]
**Describe the bug**
How to instal for Windows?

**To Reproduce**
I download gitleaks_8.2.7_windows_x64.zip
trying to start `gitleaks detect <my git repo URL>`
and i get an error:
`←[90m11:35AM←[0m ←[1m←[31mFTL←[0m←[0m Failed to get git log ←[31merror=←[0m←[31m"exec: \"git\": executable file not found in %PATH%"←[0m`

**Basic Info (please complete the following information):**
 - OS: win 10 x64
 - Gitleaks Version: 8.2.7

Could you write a complete installation instruction?
Perhaps the description of the error could be made more complete, indicating which files and in which folder are missing

**Comment by zricethezav** [comment]
@sergiomarotco 
1. `"exec: \"git\": executable file not found in %PATH%"←[0m` means you need `git` installed
2. `gitleaks` does not accept URLs, you need to clone the repo you want to scan and provide the path to it: `gitleaks detect --source=<path to repo>`

**Comment by sergiomarotco** [comment]
@zricethezav thanks comrade!

**Comment by sarthakkhanduja** [comment]
I'm sorry if I'm missing something here, but I'm unable to download `gitleaks`.

What I have done:
1. Downloaded `[gitleaks_8.18.2_windows_x64.zip](https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_windows_x64.zip)` into my "Downloads" folder (Since I thought that it's a global installation, the folder I download it in shouldn't matter)
2. When I tried running the .exe, I got a prompt saying, "This is a command line tool ..."
3. I went to my repository in VS code, opened the terminal (I am using WSL, just FYI)
4. I ran "gitleaks detect" at the root of my project directory.
5. I get an error saying "gitleaks: command not found"

What am I missing?
