### ISSUE TITLE
Add into report full link to the file with secret

### ISSUE THREAD

**Issue by sergiomarotco** [zricethezav/gitleaks#793]
**Describe the solution you'd like**
I suggest adding a full link to the secret file to the report. This will allow you to quickly open the secret file instead of looking for it in Git
Like this:
`"Match": " *** ",

  "Secret": " *** ",

  "File": " *** / *** / *** /file-with-secret.***",

  **"FileURL": "Https://git.domain/*** / *** / *** /file-with-secret.***",**

  "Commit": " *** ",`

**Comment by zricethezav** [comment]
@sergiomarotco that could be useful but I don't see an easy way to do that. How do you suggest that be accomplished?

**Comment by zricethezav** [comment]
I suppose `git remote get-url origin` could be used. However, there would need to be some translation from ssh to https if users cloned via ssh

**Comment by k0ral** [comment]
I'd like to respectfully argue that this shouldn't be `gitleaks`' responsibility :) .

Indeed, since [release `8.0.0`](https://github.com/zricethezav/gitleaks/releases/tag/v8.0.0), `gitleaks` is no longer responsible for cloning git repositories, so to be consistent, `gitleaks` should remain unaware of where the repository was cloned from.

Besides, the file URL may not be a well-defined concept:
- what if the repository has multiple remotes ?
- what if none of them is named `origin` ?
- what if the repository has no remotes ?
- as you said, is there a systematic translation from {any protocol other than HTTPS} to HTTPS ?

Finally, repeating the URL in each secret seems quite redundant: unless I am mistaken, the base URL will be identical for all files, only the file path will change. The former is a repository-level piece of information, while the latter is a finding-level one (already provided by `gitleaks`) ; this would further suggest that `gitleaks` findings aren't the right place to host that piece of information.

**Comment by sergiomarotco** [comment]
Okay, I understand you. Now I am adding the repository path to the report from the power shell. I also call Gitleaks from the power shell
