### ISSUE TITLE
gitleaks dont recognize password

### ISSUE THREAD

**Issue by EllaMozes** [zricethezav/gitleaks#860]
We have a file that contains a password :
`password=********` (contains only letters and numbers)

when we run this command : 
gitleaks detect --no-git -f json -r output.json -s <path to file> it doesn't recognise it as password
and the check is passing gitleaks

 - OS: linux
 - Gitleaks Version: 8.8.4
 
<img width="936" alt="image" src="https://user-images.githubusercontent.com/89922915/165787604-5d814242-39a8-4620-b644-e79c36d025d3.png">

<img width="326" alt="image" src="https://user-images.githubusercontent.com/89922915/165787771-2f2521b8-aada-411e-9973-8bc05a82f790.png">
 
even when we change the password to longer and more complex it still doesn't recognize it as a leak.

cc @zricethezav

**Comment by zricethezav** [comment]
@EllaMozes you can always configure your own gitleaks rule to detect passwords but the reason the password is not detected is because there are special characters in that example password that are not part of the generic credential rule. I can look into expanding the generic credential's regex alphabet for the secret capture group but that might lead to more false positives. 

In either case, I'll look into this as time permits

**Comment by EllaMozes** [comment]
Hey, thanks for replying! 
even when we use a password like this ( 7s5zy94ugr) it doesn't recognize it as a password - without any special characters 
and where is the config file which we couldn't find? or do we need to create a new one?

**Comment by zricethezav** [comment]
hi @EllaMozes, so there are a few heuristics gitleaks needs to pass when considering a secret. One of the heuristics is entropy. `7s5zy94ugr` has an entropy of [3.33](https://planetcalc.com/2476/) which does not pass the [generic rule's entropy threshold](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml#L724-L732).

Feel free to use your own config in order to detect `7s5zy94ugr`. You can read more about [custom configurations in the readme](https://github.com/zricethezav/gitleaks#configuration). Gitleaks has to balance false positives and true positives so having a higher entropy filters some of those false positives.

**Comment by EllaMozes** [comment]
sounds reasonable 
however even when I use this file and decrease the entropy to 2.0 and still doesn't recognize it as a password
furthermore, I see that  in the config file, it supposes to recognize the word 'password' (as a keyword) which is still not raising an error even when the word is hardcoded

**Comment by zricethezav** [comment]
@EllaMozes works for me:

```
➜  ~/code/zricethezav/gitleaks (master) cat tmp/tmp.txt
password = '7s5zy94ugr'

➜  ~/code/zricethezav/gitleaks (master) ./gitleaks detect --source=tmp --no-git --log-level=debug -v

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

10:01AM DBG No gitleaks config found in path tmp/.gitleaks.toml, using default gitleaks config
{
	"Description": "Generic API Key",
	"StartLine": 1,
	"EndLine": 1,
	"StartColumn": 1,
	"EndColumn": 23,
	"Match": "password = '7s5zy94ugr'",
	"Secret": "7s5zy94ugr",
	"File": "tmp/tmp.txt",
	"Commit": "",
	"Entropy": 3.321928,
	"Author": "",
	"Email": "",
	"Date": "",
	"Message": "",
	"Tags": [],
	"RuleID": "generic-api-key"
}
10:01AM INF scan completed in 10.239375ms
10:01AM WRN leaks found: 1
```

using this rule: `
```toml
[[rules]]
description = "Generic API Key"
id = "generic-api-key"
regex = '''(?i)(?:key|api[^Version]|token|pat|secret|client|password|auth)(?:[0-9a-z\-_\s.]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:=|\|\|:|<=|=>|:)(?:'|\"|\s|=|\x60){0,5}([0-9a-z\-_.=]{10,150})(?:['|\"|\n|\r|\s|\x60]|$)'''
secretGroup = 1
entropy = 3.2
keywords = [
    "key","api","token","secret","client","pat","password","auth",
]
```

> it supposes to recognize the word 'password' (as a keyword) which is still not raising an error even when the word is hardcoded

keywords string matches do not automatically flag a piece of code as a secret, keywords are used as a pre filter so gitleaks is not running regexes on regions of code that likely do not contain a secret

**Comment by zricethezav** [comment]
closing this issue for now as it can be resolved by a custom configuration
