### ISSUE TITLE
Zero-length files don't trigger `path` 

### ISSUE THREAD

**Issue by pburkholder** [zricethezav/gitleaks#873]
**Describe the bug**
I have a set of tests that I run to make sure certain patterns cause gitleaks
to fail (status 1) or succed (status 0). One of the tests relied on `touch shadow` and
it was reliably detected by v7 and a `path` rule.

In updating to 8, this behavior has changed and `touch shadow` does not 
result in a detected secret. A `path` rule is only 
triggered if the file is not zero-length.

Arguably, this isn't a bug, since a 0-length file isn't a leak, but it is 
a change from prior behavior, and kind of tripped me up.

Worth fixing?

**To Reproduce**

(I can complete this if @zricethezav agrees it's a bug)

**Expected behavior**
(ditto)

**Screenshots**

**Basic Info (please complete the following information):**
 - OS:
 - Gitleaks Version:

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@pburkholder 
0-length files are explicitly skipped [here](https://github.com/zricethezav/gitleaks/blob/master/detect/detect.go#L381-L396). As for whether this is a bug or not... I don't really have a strong opinion on it either way since this is mostly a rare edge case. If you, or someone in the community feel like contributing a patch, I'm happy to review it. Otherwise, I'll give this another month or so then close out the issue.

**Comment by zricethezav** [comment]
As stated, closing the issue
