### ISSUE TITLE
Running Gitleaks as a library throws `X error(s) occurred: * Empty buffer`

### ISSUE THREAD

**Issue by Dentrax** [zricethezav/gitleaks#910]
**Describe the bug**
Gitleaks starting to throw `X error(s) occurred: * Empty buffer` errors after upgrade from `v7` to `v8`.

**To Reproduce**

Initializing:
```go
s.detector = detect.NewDetector(s.cfg)
s.detector.Verbose = true
s.detector.Redact = true
```

```go
cloneCmd := exec.Command("git", []string{"clone", "--depth=1", cloneURL, projectClonePath}...)
cloneCmd.Stdout = os.Stdout
cloneCmd.Stderr = os.Stderr
err = cloneCmd.Start()
if err != nil {
	return fmt.Errorf("could not clone project: %s: %v\n", p.HTTPURLToRepo, err)
}

err = cloneCmd.Wait()
if err != nil {
	return fmt.Errorf("could not clone project: %s: %v\n", p.HTTPURLToRepo, err)
}

findings, err := s.detector.DetectFiles(projectClonePath)
if err != nil {
	return fmt.Errorf("[could not detect from files for project '%s' at '%s': %s\n", p.Name, projectClonePath, err.Error())
}
```

Resulted error is like following:

```
5 error(s) occurred:
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
```

I think those are throwing from [fatih/semgroup#86](https://github.com/fatih/semgroup/blob/de404588ab3d4b4ca6f8afba200b5b74994879f8/semgroup.go#L86) library.

**Expected behavior**
It should work as expected?

**Screenshots**
`-`

**Basic Info (please complete the following information):**
 - OS: `Linux`
 - Gitleaks Version: `8.8.11`

**Additional context**
* I'm using latest [gitleaks.toml](https://github.com/zricethezav/gitleaks/blob/master/config/gitleaks.toml) file

Any ideas on this? 🤔 

cc @zricethezav

**Comment by zricethezav** [comment]
@Dentrax could you provide a `--source` repo for me to reproduce this bug?

**Comment by Jeeppler** [comment]
@zricethezav I have the same issue, with more than one repository. The one example I can share with you is analyzing [PyGoat](https://github.com/adeyosemanputra/pygoat):

~~~
./gitleaks detect --log-level debug --no-git --source ~/Repos/pygoat/

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

9:51AM DBG no gitleaks config found in path ~/Repos/pygoat/.gitleaks.toml, using default gitleaks config
9:51AM ERR 12 error(s) occurred:
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
9:51AM WRN partial scan completed in 115.008714ms
9:51AM WRN 10 leaks found in partial scan
~~~

* I redacted my user name in the output: `~/Repos/pygoat/.gitleaks.toml`

This was not the only repository which I tried and got the `empty buffer` error message.

The problem is, there is no report of the findings either. Neither on stdout nor in a report file.

**Comment by zricethezav** [comment]
@Jeeppler thanks for giving me a repo I can recreate this with. I'll try and debug it asap.

w.r.t this: 

> The problem is, there is no report of the findings either. Neither on stdout nor in a report file.

You can provide `-v` which will log findings to stdout and then use `--report-path` and/or `--report-format` to save a report.

**Comment by tkreuder** [comment]
Same bug for me. I just switched back to zricethezav/gitleaks:v8.8.11 and it works (Have not tried any other previous versions).

**Comment by maltemorgenstern** [comment]
Hey @zricethezav,
we just encountered this issue - gitleaks reported five `Empty buffer` errors:
```
$ ./gitleaks detect --config config/gitleaks.toml --verbose --no-git --source my-repo

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

3:54PM ERR 5 error(s) occurred:
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
* Empty buffer
3:54PM WRN partial scan completed in 755.8516ms
3:54PM WRN no leaks found in partial scan
```

I did some trial and error testing and was able to isolate a file which breaks gitleaks. Turns out this file is a 0 byte file.
And a quick search show that exactly five empty files exist in our repository:
```
$ find . -size 0 -print
./scripts/abc/test.js
./scripts/abc/test.css
./scripts/abc/user.js
./scripts/abc/user.css
./scripts/abc/admin.css
```

If I find the time I will debug this - otherwise I hope this helps you finding the root cause.

Regards, Malte

PS: The same issue seems to be the case for pygoat mentioned by @Jeeppler:
```
$ git clone https://github.com/adeyosemanputra/pygoat.git
$ cd pygoat
$ find . -size 0 -print
./pygoat/introduction/forms.py
./pygoat/introduction/migrations/__init__.py
./pygoat/introduction/playground/readme.md
./pygoat/introduction/playground/ssrf/__init__.py
./pygoat/introduction/playground/__init__.py
./pygoat/introduction/static/css/common.css
./pygoat/introduction/templates/Lab_2021/A8_software_and_data_integrity_failure/lab3.html
./pygoat/introduction/templates/registration/logout.html
./pygoat/introduction/__init__.py
./pygoat/pygoat/__init__.py
./pygoat/test.log
./temp.py

```

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/pull/965 should fix it right up
